### ISSUE TITLE
Meta-learning Mujoco baselines s.t. Halfcheetah-Velocity

### ISSUE THREAD

**Issue by luisegehaijing** [UT-Austin-RPL/amago#68]
Hello, I found your paper very inspiring and I have seen you reported mujoco results for Halfcheeta-velocity in the paper. 
However, I don't see it contained here. By any chance you can add it here?
Many thanks!

**Comment by jakegrigsby** [comment]
Hi, 

The classic mujoco meta-RL baselines (Halfcheetah-Vel, Halfcheetah-Dir, Ant-Sparse, WalkerRandomParams, etc.) are not well standardized and all their historical results create a huge gym/gymnasium/mujoco-py version control problem. I avoid trying to maintain this in the `amago/envs/builtin/` environments, because it creates a chance that someone would use this version for the AMAGO run and another version for their other baselines. 

The best solution is to run all your baselines locally on the same env. **AMAGO can run on any gym environment** so, if the other repo you're using has a version of the env that you trust, you can train AMAGO on that exact same env. 

It'd look like `examples/01_basic_gym.py`:

```python 
def make_half_cheetah_vel):
   env = HalfCheetahVel() # from somewhere else
   env = AMAGOEnv(env, env_name="half-cheetah-vel")
   return env


....

experiment = Experiment(
           ...,
          make_train_env=make_half_cheetah_vel,
          ....
)
```

**Comment by jakegrigsby** [comment]
Hi @luisegehaijing. After we talked about this over email, I looked into bringing back the original [VariBAD](https://github.com/lmzintgraf/varibad) version that you're using (and I used in the paper).   Here are the gymnasium/mujoco requirements for this (screenshots from the repo):

![Screen Shot 2024-12-18 at 11 38 36 PM](https://github.com/user-attachments/assets/2569b45f-79e1-4a92-b08f-d0c8cb197384)
![Screen Shot 2024-12-18 at 11 41 26 PM](https://github.com/user-attachments/assets/936b1778-67a8-4a81-a6ec-78992df4ae05)

This just isn't practical to include as a built-in environment anymore. Instead, what I've done is recreate the same task using [HalfCheetah-v4](https://gymnasium.farama.org/environments/mujoco/half_cheetah/) (the most recent one we can support). 

https://github.com/UT-Austin-RPL/amago/blob/ba219ea8d60b5a06a6b9217b6293eda9fd5adb1d/amago/envs/builtin/half_cheetah_v4_vel.py#L1-L104

I've done my best to match the original task dist / reward func (velocities in [0, 3] by default, reduced control cost). This seems to lead to comparable returns to the original:

![Screen Shot 2024-12-18 at 11 47 41 PM](https://github.com/user-attachments/assets/1cf3b50a-112b-49ff-b3c7-8ea8c3000840)

But thanks to some custom logging metrics, we don't need to rely on the rewards to see if this is working; we can plot the error between the agent's velocity at the end of the episode (when it should've already figured out the correct speed) and the target:

![Screen Shot 2024-12-18 at 11 47 12 PM](https://github.com/user-attachments/assets/df75a9c7-3179-482b-8f1a-717341a1c8cb)

 And as a sanity-check, the average target task is velocity=1.5, so our agent's average vel across evals should converge to 1.5:

![Screen Shot 2024-12-18 at 11 49 53 PM](https://github.com/user-attachments/assets/3f92bc96-d73c-4bfc-bdaa-de1b6b242f1a)


I also checked that AMAGO trains fine on the standard MDP (fixed-task) version of HalfCheetah-V4 (I normally use the DMC version). Again with some custom logging I looked at the range of speeds you can reach. It's a lot higher than 3

![Screen Shot 2024-12-18 at 11 51 53 PM](https://github.com/user-attachments/assets/72394f04-1dad-4ce4-a7f8-a94a9e379d6f)

A pretty standard return on this env for a memory-free model-free baseline would be 10k. That corresponds to a vel around 10: 

![Screen Shot 2024-12-19 at 12 24 59 AM](https://github.com/user-attachments/assets/5f61fd15-7c4e-4dde-a8b7-04f5918bb058)


So I think it would be a pretty interesting to revitalize this (very saturated) benchmark task by raising the max task velocity above 10. This task requires trivial memory (reward is dense distance from target vel), so it could be cool to make it require a more complex locomotion policy to stress-test the RL details more. 


I've done a brief search over hparams and left `examples/12_half_cheetah_vel.py` in the examples. You can play around with the max task velocity with `--task_max_velocity`. An example `wandb` is [here](https://wandb.ai/jakegrigsby/amago-v3-reference/runs/pmq0owe5?nw=nwuserjakegrigsby) with command `--run_name half_cheetah_vel_max_vel3_l64 --buffer_dir buffers/ --memory_layers 3 --parallel_actors 24 --epochs 1000 --start_learning_at_epoch 2 --timesteps_per_epoch 1000 --batches_per_epoch 1400 --dset_max_size 25_000 --max_seq_len 64`. This has not been tuned for sample efficiency because this env runs so quickly.


Please note that due to changes in the underlying cheetah env, any results here would not be comparable to the originals, even if the reward funcs are as similar as I can get them.

**Comment by luisegehaijing** [comment]
Thank you Jake!! You are great!
